project_id = "ezkaucgaqlmuwzhgixgm"

[functions.consulta-cnd]
verify_jwt = false

[functions.check-cnd-vencimentos]
verify_jwt = false

[functions.send-cnd-alert]
verify_jwt = false

[functions.webhook-infosimples-callback]
verify_jwt = false

[functions.query-certificate]
verify_jwt = false

[functions.check-tarefas-vencimentos]
verify_jwt = false
